# Generated by Django 4.2.5 on 2023-11-02 06:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="essay_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="word_count_limit",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
