# Generated by Django 4.2.5 on 2023-11-03 05:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0002_subscriptionplan_essay_limit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="stripe_plan_id",
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
