# Generated by Django 4.2.5 on 2023-10-20 00:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="user_type",
            field=models.CharField(
                choices=[
                    ("TEACHER", "Teacher"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent"),
                    ("ADMINISTRATOR", "Administrator"),
                ],
                default="Student",
                max_length=15,
            ),
        ),
    ]
