# Generated by Django 4.2.5 on 2023-10-22 07:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_customuser_has_completed_onboarding"),
    ]

    operations = [
        migrations.CreateModel(
            name="GradeResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.IntegerField()),
                ("feedback", models.TextField()),
                ("numeric_grade", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grading_criteria", models.CharField(max_length=200)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("assignment_id", models.IntegerField()),
            ],
        ),
    ]
