# Generated by Django 4.2.5 on 2023-10-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_graderesult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="graderesult",
            name="assignment_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="graderesult",
            name="numeric_grade",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
    ]
