# Generated by Django 4.2.5 on 2023-10-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_graderesult_assignment_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("teacher_id", models.IntegerField()),
                ("assignment_type", models.CharField(max_length=255)),
                ("assignment_sub_type", models.CharField(max_length=255)),
                ("grade", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("desc", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=255)),
            ],
            options={
                "db_table": "assignments",
            },
        ),
    ]
