# Generated by Django 4.2.5 on 2023-10-24 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_rename_desc_assignment_task_description"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("admin_id", models.IntegerField()),
            ],
        ),
    ]
