# Generated by Django 4.2.5 on 2023-10-24 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0009_school"),
    ]

    operations = [
        migrations.DeleteModel(
            name="School",
        ),
    ]
