# Generated by Django 4.2.5 on 2023-10-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_delete_school"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("state", models.CharField(max_length=255)),
                ("country", models.CharField(max_length=255)),
                ("admin_id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("status", models.CharField(max_length=255)),
            ],
        ),
    ]
