# Generated by Django 4.2.5 on 2023-10-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="grade",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="homeroom",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="customuser",
            name="school",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
