# Generated by Django 4.2.5 on 2023-10-27 05:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_customuser_grade_customuser_homeroom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="graderesult",
            name="rubric_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
