# Generated by Django 4.2.5 on 2023-11-04 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_graderesult_assignment_name_graderesult_student_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="stripe_customer_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
