# Generated by Django 4.2.5 on 2023-11-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_remove_customuser_completed_lesson"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="referral_slots",
            field=models.IntegerField(default=2),
        ),
    ]
