# Generated by Django 4.2.5 on 2023-11-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_globalsettings"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[("English", "English"), ("Marathi", "Marathi")],
                default="English",
                max_length=20,
            ),
        ),
    ]
