# Generated by Django 4.2.5 on 2024-01-03 01:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_customuser_translation_daily_quota"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="language",
            field=models.CharField(
                choices=[
                    ("English", "English"),
                    ("Marathi", "Marathi"),
                    ("Vietnamese", "Vietnamese"),
                    ("Gujarati", "Gujarati"),
                    ("Hindi", "Hindi"),
                    ("Arabic", "Arabic"),
                    ("Spanish", "Spanish"),
                    ("Mandarin", "Mandarin"),
                    ("French", "French"),
                    ("Bengali", "Bengali"),
                    ("Russian", "Russian"),
                    ("Portuguese", "Portuguese"),
                    ("Indonesian", "Indonesian"),
                ],
                default="English",
                max_length=20,
            ),
        ),
    ]
