# Generated by Django 4.2.5 on 2024-02-01 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("genre", models.CharField(max_length=100)),
                ("subgenre", models.TextField()),
                ("step_id", models.IntegerField()),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="topics/"),
                ),
            ],
        ),
    ]
