# Generated by Django 4.2.5 on 2024-02-05 10:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CachedAPIResponse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("history", models.JSONField()),
                ("message", models.TextField()),
                ("response", models.TextField()),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["topic", "message"], name="chatbot_cac_topic_1695cd_idx"
                    )
                ],
            },
        ),
    ]
