# Generated by Django 4.2.5 on 2024-02-05 11:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0002_cachedapiresponse"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedapiresponse",
            name="audio_response",
            field=models.FileField(blank=True, null=True, upload_to="audio_responses/"),
        ),
    ]
