# Generated by Django 4.2.5 on 2024-02-06 00:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0004_alter_cachedapiresponse_history"),
    ]

    operations = [
        migrations.AddField(
            model_name="cachedapiresponse",
            name="history_hash",
            field=models.CharField(default=django.utils.timezone.now, max_length=32),
            preserve_default=False,
        ),
    ]
