# Generated by Django 4.2.5 on 2024-02-08 06:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0006_cachedapiresponse_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cachedapiresponse",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
