# Generated by Django 4.2.5 on 2024-02-08 22:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbot", "0007_alter_cachedapiresponse_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="publish",
            field=models.BooleanField(default=False),
        ),
    ]
