# Generated by Django 4.2.5 on 2023-10-25 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("v3essay_grader", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Criteria",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("criteria_name", models.CharField(max_length=255)),
                ("max_score", models.PositiveIntegerField()),
                ("criteria_desc", models.TextField()),
                ("spell_check", models.BooleanField(default=False)),
                (
                    "rubric",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="v3essay_grader.rubric",
                    ),
                ),
            ],
            options={
                "db_table": "criteria",
            },
        ),
    ]
