# Generated by Django 4.2.5 on 2023-11-06 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("v3essay_grader", "0007_sampletopic"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sampletopic",
            name="creator_id",
        ),
        migrations.AddField(
            model_name="sampletopic",
            name="creator",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
