# Generated by Django 4.2.5 on 2023-12-01 02:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("english_text", models.TextField()),
                (
                    "translated_language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Marathi", "Marathi"),
                            ("Gujarati", "Gujarati"),
                            ("Hindi", "Hindi"),
                        ],
                        max_length=20,
                    ),
                ),
                ("translated_text_user_input", models.TextField()),
                ("admin_comment", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Submitted", "Submitted"),
                            ("Reviewed", "Reviewed"),
                            ("Accepted", "Accepted"),
                        ],
                        default="Submitted",
                        max_length=20,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
