# Generated by Django 4.2.5 on 2023-12-01 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("translator", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="translation",
            name="translated_text_user_input",
            field=models.CharField(max_length=500),
        ),
    ]
