# Generated by Django 4.2.5 on 2023-11-14 01:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_id", models.IntegerField()),
                ("dialog", models.TextField()),
                (
                    "image_path",
                    models.ImageField(blank=True, null=True, upload_to="images/"),
                ),
                (
                    "audio_path",
                    models.FileField(blank=True, null=True, upload_to="audio/"),
                ),
                ("user_options", models.JSONField(blank=True, null=True)),
                ("correct_answer", models.IntegerField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="labeller.course",
                    ),
                ),
            ],
        ),
    ]
