# Generated by Django 4.2.5 on 2023-11-15 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0003_userlessonprogress"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="youtube_video_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
