# Generated by Django 4.2.5 on 2023-11-19 03:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0004_lesson_youtube_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="correct_answer_image",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
