# Generated by Django 4.2.5 on 2023-11-19 04:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0005_lesson_correct_answer_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="logos/"),
        ),
    ]
