# Generated by Django 4.2.5 on 2023-11-19 07:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0006_course_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="completion_token_bonus",
            field=models.IntegerField(default=0),
        ),
    ]
