# Generated by Django 4.2.5 on 2023-11-22 08:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0007_course_completion_token_bonus"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="transcript",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="video_link",
            field=models.TextField(blank=True, null=True),
        ),
    ]
