# Generated by Django 4.2.5 on 2023-11-22 08:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0008_course_transcript_course_video_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="timed_transcripts",
            field=models.TextField(blank=True, null=True),
        ),
    ]
