# Generated by Django 4.2.5 on 2023-11-23 04:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0010_course_creator"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="headline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
