# Generated by Django 4.2.5 on 2023-11-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0011_lesson_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="end_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
