# Generated by Django 4.2.5 on 2023-11-28 06:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0013_course_video_file_lesson_video_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="marathi_audio_path",
            field=models.FileField(blank=True, null=True, upload_to="audio/"),
        ),
        migrations.AddField(
            model_name="lesson",
            name="marathi_dialog",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="lesson",
            name="marathi_headline",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
