# Generated by Django 4.2.5 on 2023-11-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("labeller", "0014_lesson_marathi_audio_path_lesson_marathi_dialog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="marathi_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="marathi_name",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
